// <auto-generated />
using ERC;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ERC.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    [Migration("20230331160405_update calculations")]
    partial class updatecalculations
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("ERC.Calculations", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<float>("CalculationCWC")
                        .HasColumnType("REAL");

                    b.Property<float>("CalculationEE")
                        .HasColumnType("REAL");

                    b.Property<float>("CalculationEEDay")
                        .HasColumnType("REAL");

                    b.Property<float>("CalculationEENight")
                        .HasColumnType("REAL");

                    b.Property<float>("CalculationHWCCoolant")
                        .HasColumnType("REAL");

                    b.Property<float>("CalculationHWCThermalEnergy")
                        .HasColumnType("REAL");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("Calculations");
                });

            modelBuilder.Entity("ERC.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("ERC.LastIndicator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClientId")
                        .HasColumnType("INTEGER");

                    b.Property<float>("ColdWaterIndicator")
                        .HasColumnType("REAL");

                    b.Property<float>("ElectricityDayIndicator")
                        .HasColumnType("REAL");

                    b.Property<float>("ElectricityNightIndicator")
                        .HasColumnType("REAL");

                    b.Property<float>("HotWaterIndicator")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.ToTable("LastIndicators");
                });

            modelBuilder.Entity("ERC.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<float>("Rate")
                        .HasColumnType("REAL");

                    b.Property<float>("Standard")
                        .HasColumnType("REAL");

                    b.Property<string>("Unit")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("ERC.Calculations", b =>
                {
                    b.HasOne("ERC.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("ERC.LastIndicator", b =>
                {
                    b.HasOne("ERC.Client", "Client")
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });
#pragma warning restore 612, 618
        }
    }
}
